---
portage_repos:
  - name: gentoo
    default: yes
    location: /usr/portage
    sync_type: webrsync
    auto_sync: yes

  - name: hsoft
    location: /usr/portage-hsoft
    sync_type: git
    sync_uri: https://github.com/hsoft/portage-overlay.git
    auto_sync: yes

portage_packages:
  - atom: dev-vcs/git
    use: -webdav -perl -python

  - atom: app-admin/sudo
    use: -sendmail

  - atom: x11-terms/st
    savedconfig: yes

  - atom: x11-wm/dwm
    savedconfig: yes

  - atom: app-editors/vim

  - atom: app-emulation/lxd
    keyworded: yes

  # smartcard + opensc is for the yubikey
  - atom: app-crypt/gnupg
    use: smartcard

  - atom: dev-libs/opensc
    use: pcsc-lite

vim_plugins:
  - name: ctrlp
    giturl: https://github.com/ctrlpvim/ctrlp.vim.git

  - name: nerdcommenter
    giturl: https://github.com/scrooloose/nerdcommenter.git

  - name: surround
    giturl: https://github.com/tpope/vim-surround.git

  - name: syntastic
    giturl: https://github.com/vim-syntastic/syntastic.git

  - name: lightline
    giturl: https://github.com/itchyny/lightline.vim.git

  - name: vimwiki
    giturl: https://github.com/vimwiki/vimwiki.git
