---
- name: install packages
  portage:
    package: "{{ pkg.atom }}"
    state: present
  with_items: "{{ portage_packages }}"
  loop_control:
    loop_var: pkg

- include: savedconfig.yml
  with_items: "{{ portage_packages|selectattr('savedconfig', 'defined')|list }}"
  loop_control:
    loop_var: pkg
