---
# https://blog.flameeyes.eu/2014/10/setting-up-yubikey-neo-and-u2f-on-gentoo-and-linux-in-general/
- name: Create a udev rule for the yubikey
  template:
    src: "udev-yubikey-{{ use_systemd|d(False)|ternary('systemd', 'openrc') }}.rules.j2"
    dest: /etc/udev/rules.d/90-yubikey.rules
